### ISSUE TITLE
Unable to play the first song 

### ISSUE THREAD

**Issue by janvig** [sanket143/MJam#41]
The first song on the list cannot be played unless another song on the list has been played at least once.

**Comment by lilcoltsmith** [comment]
@janvig , I think I have found a solution to this. Could you assign this to me?

**Comment by lilcoltsmith** [comment]
Sorry for the confusion w/ the PRs... I believe I have it sorted out. Please let me know if you'd like things done any differently.

**Comment by AjaysinhRajput2802** [comment]
@janvig @sanket143  Can I take this issue ?

**Comment by janvig** [comment]
Sure, you can 🚀
