### ISSUE TITLE
"TypeError: state.nowplaying.instance.loop is not a function"

### ISSUE THREAD

**Issue by janvig** [sanket143/MJam#42]
Console error while rendering the _Now Playing_ bar when there is no song in the recent list.

**Comment by lilcoltsmith** [comment]
@janvig , I have found a solution to this. Could you assign this issue to me?

**Comment by lilcoltsmith** [comment]
Sorry with the confusion on the PRs... I think I have it sorted out. Please let me know if you'd like me to make any changes.

**Comment by AjaysinhRajput2802** [comment]
Is this issue open for SLoP contributor ?

**Comment by sanket143** [comment]
Yes, it's for SLoP Contributors

**Comment by AjaysinhRajput2802** [comment]
@sanket143  Can I work on it ?

**Comment by sanket143** [comment]
Sure
